definitions:
  entities.Room:
    properties:
      capacity:
        type: integer
      id:
        type: integer
    type: object
  entities.Session:
    properties:
      endTime:
        type: integer
      room:
        $ref: '#/definitions/entities.Room'
        type: object
      speaker:
        $ref: '#/definitions/entities.Speaker'
        type: object
      startTime:
        type: integer
      title:
        type: string
    type: object
  entities.Speaker:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/room:
    get:
      description: Return a list of all rooms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Room'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
      summary: Get all rooms
  /api/v1/session:
    get:
      description: Return a list of all sessions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Session'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
      summary: Get all sessions
  /api/v1/speaker:
    get:
      description: Return a list of all speakers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Speaker'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
      summary: Get all speakers
