kind: pipeline
name: default

steps:
- name: Backend-Go-Mod-Download
  image: golang:1.11.5
  volumes:
  - name: gomod_cache
    path: /go/pkg/mod
  commands:
  - cd backend
  - go mod download

- name: Backend-Gen-Swagger-Docs
  image: golang:1.11.5
  volumes:
  - name: gomod_cache
    path: /go/pkg/mod
  commands:
  - go get -u github.com/swaggo/swag/cmd/swag
  - cd backend
  - swag init

- name: Backend-Run-go-tests
  image: golang:1.11.5
  environment:
    CODECAMP_DBUSER: root
    CODECAMP_DBPASS: codecamp
    CODECAMP_DBADDR: mysql-test-db
    CODECAMP_DBNET: tcp
  volumes:
  - name: gomod_cache
    path: /go/pkg/mod
  commands:
  - cd backend
  - go test -v -tags=integration ./...

- name: Backend-gofmt
  image: golang:1.11.5
  volumes:
  - name: gomod_cache
    path: /go/pkg/mod
  commands:
  - cd backend
  - go fmt ./... | [ $(wc -l) -eq 0 ]

- name: Frontend-prettier
  image: node
  commands:
  - cd frontend
  - npm install --global prettier
  - prettier --check "**/*.ts"
  - prettier --check "**/*.html"
  
services:
- name: mysql-test-db
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: codecamp
  ports:
  - 3306

volumes:
- name: gomod_cache
  temp: {}

trigger:
  event:
  - pull_request
  - push
  branch:
  - master
    