kind: pipeline
name: default

steps:
- name: Generate-Swagger-Docs
  image: golang:1.11.5
  commands:
  - go get -u github.com/swaggo/swag/cmd/swag
  - cd backend
  - swag init

- name: Backend-Run-go-tests
  image: golang:1.11.5
  environment:
    CODECAMP_DBUSER: root
    CODECAMP_DBPASS: codecamp
    CODECAMP_DBADDR: mysqlDB
    CODECAMP_DBNET: tcp
  commands:
  - cd backend
  - go test -v -tags=integration ./...

- name: Backend-gofmt
  image: golang:1.11.5
  commands:
  - cd backend
  - go fmt ./... | [ $(wc -l) -eq 0 ]

- name: Frontend-prettier
  image: node
  commands:
  - cd frontend
  - npm install --global prettier
  - prettier --check "**/*.ts"
  - prettier --check "**/*.html"
  
services:
- name: mysqlDB
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: codecamp

trigger:
  event:
  - pull_request
  - push
  branch:
  - master
    