version: '3'
services:
  ui:
    build: ui/.
    ports:
      - "80:8080"
  backend:
    build: backend/.
    ports:
      - "81:8081"
  db:
    build: db/.
    environment:
      MYSQL_DATABASE: codecamp
      MYSQL_ROOT_PASSWORD: codecamp
    ports:
      - "3306:3306"
