basePath: '{{.BasePath}}'
definitions:
  db.Room:
    properties:
      capacity:
        type: integer
      roomName:
        type: string
    type: object
  db.Session:
    properties:
      id:
        type: integer
      name:
        type: string
      room:
        $ref: '#/definitions/db.Room'
        type: object
      speaker:
        $ref: '#/definitions/db.Speaker'
        type: object
      timeslot:
        $ref: '#/definitions/db.Timeslot'
        type: object
    type: object
  db.Speaker:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
  db.Timeslot:
    properties:
      endTime:
        type: string
      id:
        type: integer
      startTime:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: The API for the code camp counting program.
  license: {}
  title: Code Camp Counter API
  version: "1.0"
paths:
  /api/v1/room:
    get:
      description: Return a list of all rooms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Room'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
      summary: Get all rooms
  /api/v1/session:
    get:
      description: Return a list of all sessions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Session'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
      summary: Get all sessions
  /api/v1/speaker:
    get:
      description: Return a speaker with the specified email
      parameters:
      - description: Email of the requested speaker
        in: body
        name: email
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Speaker'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
      summary: Get a speaker by email
  /api/v1/speakers:
    get:
      description: Return a list of all speakers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Speaker'
            type: array
        "400":
          description: Bad Request
          schema:
            type: ""
      summary: Get all speakers
swagger: "2.0"
